### ISSUE TITLE
Estates tiles are not being updated as expected

### ISSUE THREAD

**Issue by din3** [decentraland/atlas-server#18]
LAND being listed for sale does not represent the usual sale status on the map.
Estate shown as black, while it should be indicated as light blue.

https://market.decentraland.org/contracts/0x959e104e1a4db6317fa58f8295f586e1a978c297/tokens/2641
![2021-02-13_23h33_59](https://user-images.githubusercontent.com/38725493/107862690-0fba2680-6e57-11eb-9487-606309f1f772.png)

**Comment by nachomazzara** [comment]
This happens because NFTs with the category `parcel` are not being updated if an action happens over an estate.
